### ISSUE TITLE
Define Range to Messuarements

### ISSUE THREAD

**Issue by MarlenPA** [SilverioBernal/HivesColonyAPI#1]
Veo que falto considerar que cuando se crean los tipos de medidas, es necesario tener en cuenta crear campos para cargar el rango de valores posibles.

Adjunto tabla que habia enviado con este detalle.
[Measurements Range.xlsx](https://github.com/SilverioBernal/HivesColonyAPI/files/1260919/Measurements.Range.xlsx)

**Comment by SilverioBernal** [comment]
los rangos numericos son solo enteros o tambien con decimales?

**Comment by MarlenPA** [comment]
Ya pregunte, prefieren que quede definido con dos decimales. Porque las medidas son en pulgadas y usan .25 o .50 o .75 de pulgada

**Comment by MarlenPA** [comment]
Con dos decimales

**Comment by SilverioBernal** [comment]
se crearan entidades para poder registrar los rangos de medida
